# Generated by Django 4.2.10 on 2024-03-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
    ]
