# Generated by Django 4.2.10 on 2024-03-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_tag_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
    ]
